global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: us1
    replica: 1

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['host.docker.internal:9091','127.0.0.1:9092']
  - job_name: 'sidecar'
    static_configs:
      - targets: ['host.docker.internal:19091','host.docker.internal:19092']